Update project utils

diff --git a/grepflag b/grepflag
--- a/grepflag
+++ b/grepflag
@@ -1,54 +1,66 @@
 #!/bin/bash
 
 show_help() {
-	printf "Usage: $ grepflag [FILE | [OPTIONS] DIRECTORY]\n\n"
+	printf "grepflag - A tool to find and print flag in files\nBy: r3dh4ir\n\n"
+	printf "Usage: $ grepflag [FILE | [OPTIONS] [DIRECTORY|SUB-DIRECTORIES]] \n\n"
 	echo "Strings with grepflag     $ strings flag.txt | grepflag"
-	echo "For cat binary file try   $ cat flag.img | grepflag"
+	echo "For cat binary file try   $ cat flag.img | grepflag -c"
+	echo "If non binary file try    $ grepflag flag.txt"
 	echo "OPTIONS:"
 	echo "  -r          Search recursively in directories"
+	echo "  -c, --cat   Use when a binary file to print. Only works with cat command."
 	printf "  -h, --help  Show this help message\n\n"
 	exit 0
 }
 
-regex='.*\{.+?\}'
+regex='\{[^{}]+\}'
+ors_regex='{ORS = (/}$/) ? "\n" : ""; print}'
 
 if [[ $# -eq 0 ]]; then
 	if [[ -p /dev/stdin ]]; then
-		grep -aoP "$regex" "$@"
+		pcregrep -aoM "$regex" "$@" | awk "$ors_regex"
 	else
+		printf "Error: No parameter provided.\n\n"
 		show_help
 	fi
-elif [[ $# -eq 1 ]]; then
-	if [[ -f "$1" ]]; then
-		strings_output="$(strings "$1" | grep -aoP "$regex")"
-		cat_output="$(cat "$@" | grep -aoP "$regex")"
-
-		# check if $strings_output and $cat_output is equal
-		if [ "$strings_output" = "$cat_output" ]; then
-			echo "$strings_output"
-		else
-			strings "$1" | grep -aoP "$regex" && cat "$@" | grep -aoP "$regex"
-		fi
-	fi
-elif [[ $# -eq 2 ]]; then
+elif [[ $# -gt 0 ]]; then
 	while [[ $# -gt 0 ]]; do
 		case $1 in
 		-r)
 			if [ ! -d "$2" ]; then
-				echo "Error: The parameter for -r should be a directory."
+				printf "Error: The parameter for -r should be a directory.\n\n"
 				exit 1
 			fi
 			grep -aoPr "$regex" "$@"
+			exit 1
+			;;
+		-c | --cat)
+			if [[ -p /dev/stdin ]]; then
+				grep -aoP "$regex"
+			else 
+				pritnf "Error: The parameter for -c should be run on a pipe when using cat command.\n\n"
+				show_help
+			fi
 			break
 			;;
 		-h | --help)
 			show_help
 			;;
 		*)
-			show_help
+			if [[ -f "$1" ]]; then
+				strings_output="$(strings "$1" | pcregrep -aoM "$regex" | awk "$ors_regex")"
+				cat_output="$(cat "$@" | pcregrep -aoM "$regex" | awk "$ors_regex")"
+
+				if [ "$strings_output" = "$cat_output" ]; then
+					echo "$strings_output"
+				else
+					strings "$1" | pcregrep -aoM "$regex" | awk "$ors_regex" && cat "$@" | pcregrep -aoM "$regex" | awk "$ors_regex"
+				fi
+			else 
+				printf "Error: File '%s' does not exist.\n\n" "$1"
+			fi
+			exit 1
 			;;
 		esac
 	done
-else
-	show_help
 fi
